<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Add new movie</h3>
<br />
<form class="form-horizontal" role="form" method="post" action="<?php echo "$baseUrl/manage-processor/add-new-movie"?>">


  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Movie Name" name="movieName">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Friendly Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Friendly Name" name="friendlyName">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Description" name="description">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
      	<select class="form-control" name="type">
      	<?php 
		foreach ($this->types as $type):
		/* @var $type \Models\Entities\Type */
		?>
      		<option value="<?php echo $type->getId() ?>"><?php echo $type->getTypeName() ?></option>
      	<?php endforeach;	?>
      	</select>
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Low Quality</label>
    <div class="col-sm-10">
      <select class="form-control" name="lowFile">
      	<option value="0">== choose file ==</option>
      	<?php 
		foreach ($this->files as $file):
		/* @var $file \Models\Entities\File */
		?>
      		<option value="<?php echo $file->getId() ?>"><?php echo $file->getFileName() ?></option>
      	<?php endforeach;	?>
      	</select>
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">High Quality</label>
    <div class="col-sm-10">
      <select class="form-control" name="highFile">
      	<option value="0">== choose file ==</option>
      	<?php 
		foreach ($this->files as $file):
		/* @var $file \Models\Entities\File */
		?>
      		<option value="<?php echo $file->getId() ?>"><?php echo $file->getFileName() ?></option>
      	<?php endforeach;	?>
      	</select>
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">&nbsp;</label>
    <div class="col-sm-10">
      <a href="<?php echo "$baseUrl/manage/add-new-file";?>" class="btn btn-primary">Upload new file</a>
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10" text-center>
      <button type="submit" class="btn btn-default">Add</button>
    </div>
  </div>
</form>