<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Add new server</h3>
<br />
<form class="form-horizontal" role="form" method="post" action="<?php echo "$baseUrl/manage-processor/add-new-server"?>">

<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">Protocal : </label>
		<div class="col-sm-2">
			<select class="form-control" name="protocal">
		      	<option value="http://">http-</option>
		      	<option value="https://">https-</option>
      		</select>
		</div>
	</div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Url</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Server Url" name="url">
    </div>
  </div>
  
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Add</button>
    </div>
  </div>
</form>