<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Add new Movie</h3>
<br />
<form id="form" class="form-horizontal" role="form" method="post" action="<?php echo "$baseUrl/manage-processor/add-new-movie"?>" enctype="multipart/form-data">


  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Movie Name" name="movieName">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Friendly Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Friendly Name" name="friendlyName">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Description" name="description">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
      	<select class="form-control" name="category">
      	<?php 
		foreach ($this->categories as $category):
		/* @var $category \Models\Entities\Category */
		?>
      		<option value="<?php echo $category->getId() ?>"><?php echo $category->getName() ?></option>
      	<?php endforeach;	?>
      	</select>
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Movie Url</label>
    <div class="col-sm-10">
    	<input type="text" class="form-control" id="inputEmail3" placeholder="Movie URL" name="realUrl">
    </div>
  </div>
  
 <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Cover Image</label>
    <div class="col-sm-10">
    	<input type="text" class="form-control" id="inputEmail3" placeholder="Cover Image URL" name="cover">
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Screen Shot</label>
    <div class="col-sm-10">
    	<input type="text" class="form-control" id="inputEmail3" placeholder="Screen Shot URL" name="screenShot">
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 text-center" >
      <button type="submit" class="btn btn-success" style="width: 150px;">Add</button>
    </div>
  </div>
</form>

<!-- <canvas id="c"></canvas>
<br />
<video id="v" controls="controls">
</video> -->


<script>
// 	addDocumentReady(function(){
// 		$('#form').submit(function(e){
// 			e.preventDefault();
// 			var myVid = $('#v')[0];
			
// 			addSourceToVideo(myVid, 's', 'video/mp4');
// 			//document.body.appendChild(myVid);
			
// 			myVid.load();
// // 			myVid.play();
			
// 			setTimeout(function(){
// 				start = myVid.seekable.start(0);
// 				end = Math.floor(myVid.seekable.end(0));
// 				each = end/10;
// 				var frames = new Array();
// 				i = 1;
// 				while(true){
// 				   if( i*each >= end) break;
// 				   frames[i] = Math.floor(i*each);
// // 				   alert(i*each);
// 				   i = i+1;				   
// 				}	
// 				frames[i] = end;

				
// 				console.log(frames);
// 				var w = $(myVid).width();
// 				var h = $(myVid).height();

// 				c = $('#c')[0];

// 				c.width = w;
// 				c.height = h;
				

// // 				alert($(c).width());
// // 				console.log(c);
// // 				console.log(myVid);

// // 				alert($('#c')[0].toDataURL("image/jpg") );
				
// 				ct = c.getContext('2d');
// // 				myVid.pause();

// // 				alert(i);
// // 				i=0;

// 				draw(myVid,ct,w,h,frames,1)
				
// // 				frames.forEach(function(entry) {
// // 					i++;
// // 					myVid.currentTime = entry;
// // 					ct.drawImage(myVid,0,0,w,h);	
					
					
// // // 					var dataUrl = c.toDataURL();
// // // 					window.open(dataUrl, "toDataURL() image", "width=600, height=200");
// // 				});
								
// 			},500);
			
				
			
			
// // 			end = Math.floor(myVid.seekable.end(0));	
			

			
// 			//1. ดึงค่า url
// 			//2. เอาไปใส่ tag video
// 			//3. ดึงค่าเวลาออกมาใส่ frames
// 			//4. ปรับเวลาใน video แล้ว save ค่าใส่ canvas
// 		});
// 	});


// 	function addSourceToVideo(element, src, type) {
// 	    var source = document.createElement('source');
		
// 	    source.src = src;
// 	    source.type = type;

// 	    element.appendChild(source);
// 	}
	
// 	function draw(v,c,w,h,frames,ii) {
// 		if(ii<11){
// 			v.currentTime = frames[ii];
// 			c.drawImage(v,0,0,w,h);		
// 			$('#c')[0].toDataURL("image/jpg");
// 			setTimeout(draw,500,v,c,w,h,frames,ii+1);	
// 		}
// 	}

	
</script>



