<?php 
	$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>

<div id="view-content">
	<a href="<?php echo "$baseUrl/manage/add-new-movie";?>" class="btn btn-primary">Add new Movie</a>
</div>

<br />
<table class="table table-bordered table-condense">
	<thead>
		<tr style="background-color: #8e44ad;color:white;">
			<th width="20%">Movie Name</th>
			<th width="20%">Friendly Name</th>
			<th width="30%">Description</th>
			<th width="10%">Category</th>
			<th width="20%">&nbsp;</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	$i = 0;
	$bgColor = "#9b59b6";
	foreach ($this->movies as $movie):
	/* @var $movie \Models\Entities\Movie */
	?>
		<tr <?php if(! $movie->getIsActive()) echo 'class="danger"';?> <?php if(($i++)%2!=0) echo 'style="background-color:'.$bgColor.'";' ?>>
			<td><?php echo $movie->getMovieName() ?></td>
			<td><?php echo $movie->getFriendlyName() ?></td>
			<td><?php echo $movie->getDescription() ?></td>
			<td><?php echo $movie->getCategory()->getName() ?></td>
			<?php if(!$movie->getIsActive()){?>
				<td class="text-center"><a href="<?php echo "$baseUrl/manage-processor/restore-movie?id=".$movie->getId();?>" class="btn btn-primary">Restore</a></td>
			<?php }else{?>
				<td class="text-center"><a href="<?php echo "$baseUrl/manage/update-movie?id=".$movie->getId();?>" class="btn btn-info">Update</a>
			 	<a href="<?php echo "$baseUrl/manage-processor/delete-movie?id=".$movie->getId();?>" class="btn btn-danger">Delete</a></td>
			<?php }?>
			</tr>	
	<?php 
	endforeach;	
	?>
	</tbody>
</table>