<?php 
	$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<a href="<?php echo "$baseUrl/manage/add-new-server";?>" class="btn btn-primary">Add new server</a>
<br /><br />
<table class="table table-bordered table-condense">
	<thead>
		<tr>
			<th width="10%" class="text-center">id</th>
			<th width="70%">url</th>
			<th width="20%">#action</th>
		</tr>
	</thead>
	<tbody>
	<?php 
	foreach ($this->servers as $server):
	/* @var $server \Models\Entities\Server */
	?>
		<tr <?php if(! $server->getIsActive()) echo 'class="danger"';?>>
			<td class="text-center"><?php echo $server->getId() ?></td>
			<td><?php echo $server->getTriggerUrl() ?></td>
			<?php if(!$server->getIsActive()){?>
				<td class="text-center"><a href="<?php echo "$baseUrl/manage-processor/restore-server?id=".$server->getId();?>" class="btn btn-primary">Restore</a></td>
			<?php }else{?>
				<td class="text-center"><a href="<?php echo "$baseUrl/manage/update-server?id=".$server->getId();?>" class="btn btn-primary">Update</a>
			 	<a href="<?php echo "$baseUrl/manage-processor/delete-server?id=".$server->getId();?>" class="btn btn-primary">Delete</a></td>
			<?php }?>
			</tr>	
	<?php 
	endforeach;	
	?>
	</tbody>
</table>