<?php 
	$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<a href="<?php echo "$baseUrl/manage/add-new-type";?>" class="btn btn-primary">Add new Category</a>
<br /><br />
<table class="table table-bordered table-condense">
	<thead>
		<tr>
			<th width="30%">Name</th>
			<th width="40%">Description</th>
			<th width="10%">Sorting</th>
			<th width="20%"></th>
		</tr>
	</thead>
	<tbody>
	<?php 
	foreach ($this->types as $type):
	/* @var $type \Models\Entities\Type */
	?>
		<tr>
			<td><?php echo $type->getName() ?></td>
			<td><?php echo $type->getDescription() ?></td>
			<td><?php echo $type->getSortingOrder() ?></td>
			<?php if(!$type->getIsActive()){?>
				<td class="text-center"><a href="<?php echo "$baseUrl/manage-processor/restore-type?id=".$type->getId();?>" class="btn btn-primary btn-xs">Restore</a></td>
			<?php }else{?>
				<td class="text-center"><a href="<?php echo "$baseUrl/manage/update-type?id=".$type->getId();?>" class="btn btn-info btn-xs">Update</a>
			 	<a href="<?php echo "$baseUrl/manage-processor/delete-type?id=".$type->getId();?>" class="btn btn-danger btn-xs">Delete</a></td>
			<?php }?>
			</tr>	
	<?php 
	endforeach;	
	?>
	</tbody>
</table>