<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Update Movie</h3>
<br />
<form class="form-horizontal" role="form" method="post" action="<?php echo "$baseUrl/manage-processor/update-movie"?>" enctype="multipart/form-data">
<input type="hidden" name="id" value="<?php echo $this->movie->getId() ?>" />

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Movie Name" name="movieName" value="<?php echo $this->movie->getMovieName() ?>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Friendly Name</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Friendly Name" name="friendlyName" value="<?php echo $this->movie->getFriendlyName() ?>">
    </div>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="inputEmail3" placeholder="Description" name="description" value="<?php echo $this->movie->getDescription() ?>">
    </div>
  </div>
 <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Category</label>
    <div class="col-sm-10">
      	<select class="form-control" name="category">
      	<?php 
		foreach ($this->categories as $category):
		/* @var $category \Models\Entities\Category */
		?>
      		<option value="<?php echo $category->getId() ?>" <?php echo ($category->getId()==$this->movie->getCategory()->getId()) ? "selected" : "" ?>><?php echo $category->getName() ?></option>
      	<?php endforeach;	?>
      	</select>
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Low Quality File</label>
    <div class="col-sm-10">
    	<input type="text" class="form-control" id="inputEmail3" placeholder="Low Quality File URL" name="lowQualityFile" value="<?php echo $this->movie->getLowQualityFile() ?>">
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">High Quality File</label>
    <div class="col-sm-10">
    	<input type="text" class="form-control" id="inputEmail3" placeholder="High Quality File URL" name="highQualityFile" value="<?php echo $this->movie->getHighQualityFile() ?>">
    </div>
  </div>
  
   <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Cover Image</label>
    <div class="col-sm-10">
    	<input type="file" name="cover" class="form-control">
    </div>
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Screen Shot</label>
    <div class="col-sm-10">
    	<input type="file" name="screenShot[]" multiple="multiple" class="form-control">
    </div>
  </div>
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 text-center">
      <button type="submit" class="btn btn-success" style="width:150px">Update</button>
    </div>
  </div>
</form>