<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Update server</h3>
<br />
<form class="form-horizontal" role="form" method="post" action="<?php echo "$baseUrl/manage-processor/update-server"?>">


  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Url</label>
    <div class="col-sm-10">
    	<input type="hidden" name="id" value="<?php echo $this->server->getId() ?>" />
      <input type="text" class="form-control" id="inputEmail3" placeholder="Server Url" name="url" value="<?php echo $this->server->getUrl() ?>">
    </div>
  </div>
  
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Update</button>
    </div>
  </div>
</form>