<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Update Category</h3>
<br />
<form class="form-horizontal" role="form" method="post" action="<?php echo "$baseUrl/manage-processor/update-type"?>">


    <input type="hidden" name="id" value="<?php echo $this->type->getId() ?>" />

 <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">      
    <input type="text" class="form-control" id="inputEmail3" placeholder="Type" name="type" value="<?php echo $this->type->getName() ?>">
    </div>
  </div>
 <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">      
    <input type="text" class="form-control" id="inputEmail3" placeholder="Description" name="description" value="<?php echo $this->type->getDescription(); ?>">
    </div>
  </div>
  
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10 text-center">
      <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
</form>