<?php $baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();?>
<br />
<h3 class="text-center">Upload new movie(s)</h3>
<br />
<form class="form-horizontal text-center" role="form" action="<?php echo "$baseUrl/manage-processor/upload-new-movie"?>">
	<input type="hidden" name="url" id="url" value="<?php echo "$baseUrl/manage-processor/upload-new-movie"?>" />
	<div class="form-group">
		<label for="inputEmail3" class="col-sm-2 control-label">Select Server : </label>
		<div class="col-sm-8">
			<select class="form-control" name="server" id="server">
		      	<?php 
				foreach ($this->servers as $server):
				/* @var $server \Models\Entities\Server */
				?>
		      		<option value="<?php echo $server->getUrl() ?>"><?php echo $server->getTriggerUrl() ?></option>
		      	<?php endforeach;	?>
      		</select>
		</div>
	</div>
	<div class="form-group">
		<label for="file" class="col-sm-2 control-label">Choose File : </label>
		<div class="col-sm-8">
			<input id="file" name="file" type="file" multiple="multiple">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-2 control-label">&nbsp;</label>
		<div class="col-sm-8">
			<a href="#" onclick="sendFile(); return false;" class="btn btn-primary">Upload</a>
		</div>
	</div>
	
</form>

<div class="container"
	style="overflow-x: hidden; overflow-y: auto; height: 70%; margin-top: 20px;">
	<table class="table table-bordered table-condense" id="myTable">
		<thead>
			<tr>
				<td><span style="font-weight: bolder;">#</span></td>
				<td><span style="font-weight: bolder;">filename</span></td>
				<td><span style="font-weight: bolder;">status</span></td>
			</tr>
		</thead>
		<tbody>
		</tbody>
	</table>
</div>