<?php 
	$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>

<section>
<h4 style="margin-bottom: 20px;margin-top: 20px;">NEW VIDEOS - This page is updated everyday with new pron videos!</h4>
<div class="row" style="margin-bottom: 30px;">
	<div class="col-xs-9" style="">
	
		<?php 
		
			/* @var $movie \Models\Entities\Movie */
			foreach ($this->movies as $movie):
// 			$cover = $movie->getCover() ? "$baseUrl/uploaded-images/{$movie->getCover()->getRealKey()}": "$baseUrl/images/no-cover.jpg";
			$cover = $movie->getCoverUrl();
			?>
			
		<div class="movie movie-thumbnail">			
			<img src="<?php echo "$cover"?>" 
			alt="Cover image of <?php echo $movie->getMovieName()?>" class="img-thumbnail" style="width: 98%;">
			<p style="padding: 5px 10px;">
				<a href="<?php echo "$baseUrl/watch/{$movie->getId()}/{$movie->getFriendlyName()}"?>">
					<?php echo $movie->getMovieName()?>
				</a>
			</p>
		</div>
			
			<?php 	
			endforeach;
		?>
		
		<div style="clear:both; margin:0 auto; text-align: center;">
		<?php $this->navigation->render();?>
		</div>
		
		<div style="clear:both; width: 100%; position: relative;">
			<?php include 'ad2.php';?>
		</div>
		
	</div>
	<div class="col-xs-3">
		<?php include 'ad1.php';?>
	</div>
</div>



</section>

<script>
	addDocumentReady(function(){
		$('.movie').click(function(){
			window.location.href=$(this).find('a').attr('href');
		});
	});
</script>