<footer style="background-color: #95a5a6; margin-left:-15px; margin-right: -15px; color: black; padding-bottom: 0px; height:60px; padding-top: 10px;">
	<!-- 
	<p style="padding: 10px; font-size: 11px;">
		XVideos.com is a free hosting service for porn videos. We convert your files to flash flv format (you need to have adobe flash plugin installed on your computer to view the videos) and generate a page that you can link to. You can also grab our 'embed code' to display any video on another website. Every video uploaded, is shown on our indexes more or less three days after uploading. About 1200 to 2000 adult videos are uploaded each day (note that gay and shemale videos are filtered from this page, but shown in their respective categories). Our pages (everything that you see hosted on www.xvideos.com) contain absolutely no spyware/adware/trojan/etc. There is no charge (no hidden charges either) for viewing our videos.
	</p>
	<p class="text-center" style="font-size: 12px;">
		We are often asked how to download videos from tube sites (flash videos). Download and install this, it works with our sites too.
	</p>
	<p class="text-center" style="font-size: 12px;">
		XVIDEOS is rated with RTA label. Parents, you can easily block access to this site. Please read this page for more informations.
	</p>
	
	-->
	
	<p class="text-center" style="font-size: 14px; font-weight: bold;">
		ติดต่อโฆษณา: &nbsp; iiisex.advertisement@gmail.com
		<br />
		request หนัง/หมวดหมู่หนัง: &nbsp; iiisex.movies@gmail.com
		<br />
		
	</p>
</footer>