<?php 
	use My\Factory\MyEntityManagerFactory;
$repo = MyEntityManagerFactory::getEntityManager()->getRepository('\Models\Entities\Category');
$cats = $repo->findBy(array('isActive'=>true), array('order'=>'asc'));
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

?>
<header style="/*margin-left: -15px;*/ position: relative;">
	<div style="float:left;">
		<a href="design.php">
		<img src="img/logo.png" style="height: 100px;">
		</a>
	</div>
	<div style="width: 320px; position: absolute; right: 0px; bottom: 55px; z-index: 100;">
		<form class="form-inline" role="search" style="margin: 5px 0px;">
			<div class="form-group" style="display: inline-block;">			
				<div class="input-group">	
					<span class="input-group-addon"><span
						class="glyphicon glyphicon-search"></span></span> 
					<input	type="text" class="form-control" placeholder="Search for videos" style="width: 200px;">
					<button type="submit" class="btn btn-default">Search</button>
				</div>
			</div>
		</form>
	</div>	
	
	<div class="clear"></div>
	
	
	
	
<nav class="navbar navbar-default" role="navigation" id="navbar" style="margin-left: -15px; margin-right: -15px;">
    <ul class="nav navbar-nav">
    <?php 
     foreach ($cats as $cat):
     	echo "<li><a href=\"$baseUrl/category/{$cat->getId()}\">{$cat->getName()}</a></li>";
     endforeach;
    ?>
    </ul>
</nav>
</header>