<?php
/* @var $layoutManager My\Manager\MyLayoutManager */
$layoutManager = $this->layoutManager;
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="UTF-8" />
<meta name="author" content="Mapkuff">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="stats-in-th" content="029e" />

<?php echo $layoutManager->getTitle()?>
<?php echo $layoutManager->getDescription()?>
<?php echo $layoutManager->getKeyword()?>
<?php echo $layoutManager->getRobot()?>


<link href="<?php echo $baseUrl;?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="<?php echo $baseUrl;?>/bootstrap/css/non-responsive.css" rel="stylesheet" />
<link href="<?php echo $baseUrl;?>/css/front.css" rel="stylesheet" />
<?php echo $layoutManager->getAdditionalCssString()?>
<?php echo $layoutManager->getAdditionalHeaderTagString()?>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="<?php echo $baseUrl;?>/js/html5shiv.js"></script>
<script src="<?php echo $baseUrl;?>/js/respond.min.js"></script>
<![endif]-->
</head>

<body style="background-color: #bdc3c7">  	
<script src="<?php echo $baseUrl;?>/js/documentReady.js"></script>

<div class="container" id="wrapper" style="background-color: #ecf0f1;">	
<?php echo $this->render('/_global/header.phtml');?>
<?php echo $layoutManager->getContent(); ?>
<?php echo $this->render('/_global/footer.phtml');?>
</div>

<script src="<?php echo $baseUrl;?>/js/jquery.js"></script>
<script src="<?php echo $baseUrl;?>/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $baseUrl;?>/js/front.js"></script>
<script type="text/javascript">
	addDocumentReady(function(){
		if($('.prettyphoto')[0]){
			$('.prettyphoto').prettyPhoto();			
		}
	});
</script>
<?php echo $layoutManager->getAdditionalJavascriptString()?>
<?php echo $layoutManager->getContentScript(); ?>
</body>
</html>