<?php
/* @var $layoutManager My\Manager\MyLayoutManager */
$layoutManager = $this->layoutManager;
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<!DOCTYPE html>
<html lang="th">
<head>
<meta charset="UTF-8" />
<meta name="author" content="Mapkuff">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="stats-in-th" content="029e" />

<?php echo $layoutManager->getTitle()?>
<?php echo $layoutManager->getDescription()?>
<?php echo $layoutManager->getKeyword()?>
<?php echo $layoutManager->getRobot()?>


<link href="<?php echo $baseUrl;?>/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="<?php echo $baseUrl;?>/css/front.css" rel="stylesheet" />
<link href="<?php echo $baseUrl;?>/css/ress.css" rel="stylesheet" />
<link href="<?php echo $baseUrl;?>/css/locationpicker.css" rel="stylesheet" />
<link href="<?php echo $baseUrl;?>/css/prettyPhoto.css" rel="stylesheet" />
<?php echo $layoutManager->getAdditionalCssString()?>
<?php echo $layoutManager->getAdditionalHeaderTagString()?>

<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="<?php echo $baseUrl;?>/js/html5shiv.js"></script>
<script src="<?php echo $baseUrl;?>/js/respond.min.js"></script>
<![endif]-->
</head>

<body style="background-color: #eaeaea; color: #2c3e50;">
<script src="<?php echo $baseUrl;?>/js/documentReady.js"></script>
<?php echo $layoutManager->getContent(); ?>
<script src="<?php echo $baseUrl;?>/js/jquery.js"></script>
<script src="<?php echo $baseUrl;?>/bootstrap/js/bootstrap.min.js"></script>
<script src="<?php echo $baseUrl;?>/js/front.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?sensor=true"></script>
<script src="<?php echo $baseUrl;?>/js/locationpicker.js"></script>
<script src="<?php echo $baseUrl;?>/js/prettyPhoto.js"></script>
<script type="text/javascript">
	addDocumentReady(function(){
		if($('.prettyphoto')[0]){
			$('.prettyphoto').prettyPhoto();			
		}
	});
</script>
<?php echo $layoutManager->getAdditionalJavascriptString()?>
<?php echo $layoutManager->getContentScript(); ?>
<div style="position: fixed; bottom: 0px; z-index: 1000; width: 100%;">
	<div style="width: 20px; margin: 0 auto;">
		<script type="text/javascript" language="javascript1.1" src="http://tracker.stats.in.th/tracker.php?sid=56141"></script><noscript><a target="_blank" href="http://www.stats.in.th/">www.Stats.in.th</a></noscript>
	</div>
</div>
</body>
</html>