<?php 
use Models\Services\VideoService;
use \Doctrine\Common\Collections\ArrayCollection;

	$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
	/* @var $movie \Models\Entities\Movie */
	$movie = $this->movie;
// 	$cover = $movie->getCover() ? "$baseUrl/uploaded-images/{$movie->getCover()->getRealKey()}": "$baseUrl/images/no-cover.jpg";
	$cover = $movie->getCoverUrl();
	$vids = unserialize($movie->getProcessedUrl());
	
	$remoteAddr = Zend_Controller_Front::getInstance()->getRequest()->getServer('REMOTE_ADDR');
?>

<section>
	<!-- 
	<h4 style="margin-bottom: 20px; margin-top: 20px;">NEW VIDEOS - This
		page is updated everyday with new pron videos!</h4>-->
	
	<div class="row" style="margin-bottom: 30px; margin-top: 30px;">
		<div class="col-lg-9" style="">
			<div style="margin-left: 15px;">
			<video id="main-vid" class="video-js vjs-default-skin"
				controls preload="auto" width="640" height="360"
				poster="<?php echo $cover?>"
				data-setup='{}'>
				<?php 
				$default = 'data-default="true"';
				foreach ($vids as $res=>$vid):
					$vid = preg_replace('/[0-9]{1,3}[\.]{1}[0-9]{1,3}[\.]{1}[0-9]{1,3}[\.]{1}[0-9]{1,3}/', $remoteAddr, $vid);
				?>
					<source data-res="<?php echo $res?>" src="<?php echo $vid;?>"
					type="video/mp4" <?php echo $default;?> />
				
				<?php 
				$default = '';
				endforeach;?>
			</video>
			<div style="float: left;">
			<h3 style=""><?php echo $movie->getMovieName();?></h3>
			<p style="font-size: 14px; font-weight: bold; margin-top: 15px;">จำนวนผู้เข้าชม: <?php echo $movie->getViewCount()?></p>
			
			</div>
			<div style="float: right; margin-right: 40px;"> 
				<!-- 
				<a href="javascript:void(0)" class="btn btn-default" onclick="play360();">
					LD 360P
				</a>
				<br />
				<a href="javascript:void(0)" class="btn btn-default" onclick="play720();">
					HD 720P
				</a>
				 -->
			</div>
			
			<div style="clear:both;"></div>
			<p style="font-size: 16px; font-weight: bold; margin-top: 50px; text-align: center;">Watch more videos</p>
			</div>
	
		
	
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
  	<?php 
  	$relatedMovies = new ArrayCollection($this->relatedMovies);
  	$it = $relatedMovies->getIterator();
  	$it->rewind();
  	$count = 0;
  	$itCount = $it->count();
  	$itemClass = "item active";
  	
			/* @var $movie \Models\Entities\Movie */
  	if(true):
	while($count<=$itCount):
		if($count==9):
			$count = 1;
			$itCount-= 9;
		else:
			$count++;
		endif;
		$movie = $it->current();
		$cover = $movie->getCoverUrl();
		
		if($count == 1):
			echo '<div class="'.$itemClass.'" style="min-height:570px;">';
			$itemClass = 'item';
		endif;
	
	
// 			$cover = $movie->getCover() ? "$baseUrl/uploaded-images/{$movie->getCover()->getRealKey()}": "$baseUrl/images/no-cover.jpg";
			
			
			?>
			
		<div class="movie movie-thumbnail" style="width: 32%;">			
			<img src="<?php echo "$cover"?>" 
			alt="Cover image of <?php echo $movie->getMovieName()?>" class="img-thumbnail" style="width:219px; height:150px;"
			data-url1 = "<?php echo $movie->getCoverUrl()?>" 
			data-url2 = "<?php echo $movie->getScreenShotUrl()?>" 
			>
			<p style="padding: 5px 10px;">
				<a href="<?php echo "$baseUrl/watch/{$movie->getId()}/{$movie->getFriendlyName()}"?>">
					<?php echo $movie->getMovieName()?>
					
				</a>
			</p>
		</div>
			
			<?php 	
		if($count == 9):
			echo '</div>';
		endif;
	endwhile;
	endif;
		?>
  
  
  
    
    
    </div>
  </div>
  <p class="text-center">
  <a class=" btn btn-danger" href="#carousel-example-generic" data-slide="next">
    <!-- <span class="glyphicon glyphicon-chevron-right"></span> -->
    Load more videos
  </a>
  </p>
</div>
		
		
		</div>
		<div class="col-lg-3">
		<div style="clear:both; width: 120%; position: relative; margin-left: -40px;">
				<?php include 'ad1.php';?>
		</div>
		</div>
		
		<div class="col-lg-12">		
		<div style="clear:both; width: 100%; position: relative; margin-top: 30px;">
			<?php include 'ad2.php';?>
		</div>
	</div>
	</div>



</section>

<script>
	var xxx;
	addDocumentReady(function(){
		$('.movie').click(function(){
			window.location.href=$(this).find('a').attr('href');
		});


		prepareSrc();
		
		vjs('main-vid', {
	        plugins: {
	          resolutions: true
	        }
	    });
	    console.log(xxx);


	    $('.movie img').hover(function(){
		    var anotherUl = $(this).attr('data-url2');
			$(this).attr('src',anotherUl);
		},function(){
			var anotherUl = $(this).attr('data-url1');
			$(this).attr('src',anotherUl);
		});
	});


	var v360 = "";
	var v720 = "";
	function prepareSrc(){
		v360 = $('#main-vid source[data-res="360"]').attr('src');
		v720 = $('#main-vid source[data-res="720"]').attr('src');
	}

	function play360(){
		var vid = $('#main-vid_html5_api')[0];
		vid.pause();
		var ctime = vid.currentTime;
		$(vid).attr('src',v360);
		vid.currentTime = ctime;
		vid.play();		
	}

	function play720(){
		var vid = $('#main-vid_html5_api')[0];
		vid.pause();
		var ctime = vid.currentTime;
		$(vid).attr('src',v720);
		vid.currentTime = ctime;
		vid.play();				
	}
</script>