<?php 
	use Models\Services\VideoService;
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();
	/* @var $movie \Models\Entities\Movie */
	$movie = $this->movie;
// 	$cover = $movie->getCover() ? "$baseUrl/uploaded-images/{$movie->getCover()->getRealKey()}": "$baseUrl/images/no-cover.jpg";
	$cover = $movie->getCoverUrl();
	$vids = unserialize($movie->getProcessedUrl());
?>

<section>
	<h4 style="margin-bottom: 20px; margin-top: 20px;">NEW VIDEOS - This
		page is updated everyday with new pron videos!</h4>
	<div class="row" style="margin-bottom: 30px;">
		<div class="col-xs-9" style="">
			<div style="margin-left: 30px;">
			<video id="main-vid" class="video-js vjs-default-skin"
				controls preload="auto" width="640" height="360"
				poster="<?php echo $cover?>"
				data-setup='{}'>
				<?php 
				$default = 'data-default="true"';
				foreach ($vids as $res=>$vid):?>
					<source data-res="<?php echo $res?>" src="<?php echo $vid;?>"
					type="video/mp4" <?php echo $default;?> />
				
				<?php 
				$default = '';
				endforeach;?>
			</video>
			</div>
	
		<?php 
		
			
			foreach (array() as $movie):
			break;
			$cover = $movie->getCover() ? "$baseUrl/uploaded-images/{$movie->getCover()->getRealKey()}": "$baseUrl/images/no-cover.jpg";
			?>
			
		<div class="movie movie-thumbnail">
				<img src="<?php echo "$cover"?>"
					alt="Cover image of <?php echo $movie->getMovieName()?>"
					class="img-thumbnail" style="width: 98%;">
				<p style="padding: 5px 10px;">
					<a
						href="<?php echo "$baseUrl/watch/{$movie->getId()}/{$movie->getFriendlyName()}"?>">
					<?php echo $movie->getMovieName()?>
				</a>
				</p>
			</div>
			
			<?php 	
			endforeach;
		?>
		
		
		<div style="clear: both; width: 100%; position: relative; margin-top: 100px;">
			<?php include 'ad2.php';?>
		</div>

		</div>
		<div class="col-xs-3">
		<?php include 'ad1.php';?>
	</div>
	</div>



</section>

<script>
	addDocumentReady(function(){
		$('.movie').click(function(){
			window.location.href=$(this).find('a').attr('href');
		});

		vjs('main-vid', {
	        plugins: {
	          resolutions: true
	        }
	    });
	});
</script>